# creating deployments and service for mongo in same file 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo
  template: # ---- this will defined the blue print ------
    metadata:
      labels: # --- labels are key/value pairs that are attached to k8s resources. Labels are additional identifiers
        app: mongo 
    spec:
      containers:
      - name: mongodb
        image: mongo:nanoserver-ltsc2022
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service # -- this is what we defined in mongo-config map ---
spec:
  selector:
    app: mongo # -- this should match with app name in deployment given above --
  ports:
    - protocol: TCP
      port: 27017 #-- it can be anything, but to keep simple we can give same port ---
      targetPort: 27017 # -- this should match with containerPort in deployment given above --
