apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: pastevalue #echo -n mongouser | base64 -> paste the value 
  mongo-password: pastevalue #echo -n mongopassword | base64 -> paste the value